

layersGIS = ['layer-0-1876-09-San-Felipe-Hurriciane.geojson', 'layer-1-1878-10-Gale-of-1878.geojson', 'layer-2-1879-08-Unnamed-Hurricane-#2.geojson', 'layer-3-1887-08-Unnamed-Hurricane-#6.geojson', 'layer-4-1887-08-Unnamed-Hurricane-#7.geojson', 'layer-5-1893-08-Unnamed-Hurricane-#4.geojson', 'layer-6-1893-10-Charleston-Hurricane.geojson', 'layer-7-1899-08-San-Ciriaco-Hurricane.geojson', 'layer-8-1899-10-Unnamed-Hurricane-#8.geojson', 'layer-9-1924-08-Unnamed-Hurricane-#2.geojson', 'layer-10-1926-09-Miami-Hurricane.geojson', 'layer-11-1933-08-Chesapeake-Potomac-Hurricane.geojson', 'layer-12-1933-09-Outer-Banks-Hurricane.geojson', 'layer-13-1936-09-Unnamed-Hurricane-#13.geojson', 'layer-14-1938-09-Long-Island-Express.geojson', 'layer-15-1944-09-Great-Atlantic-Hurricane.geojson', 'layer-16-1954-08-Hurricane-Carol.geojson', 'layer-17-1954-10-Hurricane-Hazel.geojson', 'layer-18-1969-08-Hurricane-Camille.geojson', 'layer-19-1972-06-Hurricane-Agnes.geojson', 'layer-20-1985-09-Hurricane-Gloria.geojson', 'layer-21-1995-08-Hurricane-Felix.geojson', 'layer-22-1996-09-Hurricane-Fran.geojson', 'layer-23-1999-09-Hurricane-Floyd.geojson', 'layer-24-2003-09-Hurricane-Isabel.geojson']

serversGIS = ['https://arcgis.vdem.virginia.gov/arcgis/rest/services/Hazards/Hurricane_StormTracks/MapServer/0', 'https://arcgis.vdem.virginia.gov/arcgis/rest/services/Hazards/Hurricane_StormTracks/MapServer/1', 'https://arcgis.vdem.virginia.gov/arcgis/rest/services/Hazards/Hurricane_StormTracks/MapServer/2', 'https://arcgis.vdem.virginia.gov/arcgis/rest/services/Hazards/Hurricane_StormTracks/MapServer/3', 'https://arcgis.vdem.virginia.gov/arcgis/rest/services/Hazards/Hurricane_StormTracks/MapServer/4', 'https://arcgis.vdem.virginia.gov/arcgis/rest/services/Hazards/Hurricane_StormTracks/MapServer/5', 'https://arcgis.vdem.virginia.gov/arcgis/rest/services/Hazards/Hurricane_StormTracks/MapServer/6', 'https://arcgis.vdem.virginia.gov/arcgis/rest/services/Hazards/Hurricane_StormTracks/MapServer/7', 'https://arcgis.vdem.virginia.gov/arcgis/rest/services/Hazards/Hurricane_StormTracks/MapServer/8', 'https://arcgis.vdem.virginia.gov/arcgis/rest/services/Hazards/Hurricane_StormTracks/MapServer/9', 'https://arcgis.vdem.virginia.gov/arcgis/rest/services/Hazards/Hurricane_StormTracks/MapServer/10', 'https://arcgis.vdem.virginia.gov/arcgis/rest/services/Hazards/Hurricane_StormTracks/MapServer/11', 'https://arcgis.vdem.virginia.gov/arcgis/rest/services/Hazards/Hurricane_StormTracks/MapServer/12', 'https://arcgis.vdem.virginia.gov/arcgis/rest/services/Hazards/Hurricane_StormTracks/MapServer/13', 'https://arcgis.vdem.virginia.gov/arcgis/rest/services/Hazards/Hurricane_StormTracks/MapServer/14', 'https://arcgis.vdem.virginia.gov/arcgis/rest/services/Hazards/Hurricane_StormTracks/MapServer/15', 'https://arcgis.vdem.virginia.gov/arcgis/rest/services/Hazards/Hurricane_StormTracks/MapServer/16', 'https://arcgis.vdem.virginia.gov/arcgis/rest/services/Hazards/Hurricane_StormTracks/MapServer/17', 'https://arcgis.vdem.virginia.gov/arcgis/rest/services/Hazards/Hurricane_StormTracks/MapServer/18', 'https://arcgis.vdem.virginia.gov/arcgis/rest/services/Hazards/Hurricane_StormTracks/MapServer/19', 'https://arcgis.vdem.virginia.gov/arcgis/rest/services/Hazards/Hurricane_StormTracks/MapServer/20', 'https://arcgis.vdem.virginia.gov/arcgis/rest/services/Hazards/Hurricane_StormTracks/MapServer/21', 'https://arcgis.vdem.virginia.gov/arcgis/rest/services/Hazards/Hurricane_StormTracks/MapServer/22', 'https://arcgis.vdem.virginia.gov/arcgis/rest/services/Hazards/Hurricane_StormTracks/MapServer/23', 'https://arcgis.vdem.virginia.gov/arcgis/rest/services/Hazards/Hurricane_StormTracks/MapServer/24']

for layerGIS in layersGIS:
	print layerGIS

for serverGIS in serversGIS:
	print serverGIS

